Repository sparcs-kaist/new-ara-app, pull requests merged in 2024-07, with the labels that each got.

#204 PostWritePage 번역되지 않은 부분 보완
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  ios/Runner/Info.plist
  lib/pages/post_write_page.dart
Labels: bug

#205 PostListShowPage 말머리 필터 추가
  lib/pages/post_list_show_page.dart
  lib/utils/with_school.dart
Labels: enhancement

#206 PostWritePage에 나가기 확인 dialog 추가
  assets/translations/en.json
  assets/translations/ko.json
  lib/pages/post_write_page.dart
  lib/translations/codegen_loader.g.dart
  lib/translations/locale_keys.g.dart
  lib/widgets/dialogs.dart
Labels: enhancement

#208 Feat/add block number info dialog
  .fvm/fvm_config.json
  .fvmrc
  .gitignore
  assets/translations/en.json
  assets/translations/ko.json
  lib/pages/post_view_page.dart
  lib/translations/codegen_loader.g.dart
  lib/translations/locale_keys.g.dart
  lib/widgets/dialogs.dart
Labels: enhancement, good first issue

#207 Feat: 본인 댓글 '글쓴이' fontColor 변경
  .fvm/fvm_config.json
  .fvmrc
  .gitignore
  lib/pages/post_view_page.dart
Labels: enhancement
