Repository sparcs-kaist/new-ara-app, pull requests merged in 2024-09, with the labels that each got.

#219 Caching 속도 최적화 및 임시 저장 수정
  lib/pages/post_write_page.dart
  lib/utils/cache_function.dart
Labels: bug

#230 첨부파일 캐싱
  assets/translations/en.json
  assets/translations/ko.json
  ios/Podfile.lock
  ios/fastlane/Fastfile
  lib/pages/main_page.dart
  lib/pages/post_write_page.dart
  lib/providers/user_provider.dart
  lib/translations/codegen_loader.g.dart
  lib/translations/locale_keys.g.dart
Labels: enhancement

#233 Chore/deploy 1.2.0
  android/Gemfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  pubspec.yaml
Labels: chore
