Repository sparcs-kaist/new-ara-app, pull requests merged in 2024-02, with the labels that each got.

#43 Fix: webview 오류 태그 수정 및 폰트 설정
  lib/utils/html_info.dart
Labels: bug

#55 Design/bulletin search page
  lib/constants/board_type.dart
  lib/pages/bulletin_list_page.dart
  lib/pages/bulletin_search_page.dart
  lib/providers/user_provider.dart
  lib/utils/create_dio_with_config.dart
Labels: enhancement

#41 숨겨진 글 관련 디자인, 처리 로직 구현
  ios/Podfile.lock
  lib/pages/main_page.dart
  lib/pages/post_list_show_page.dart
  lib/pages/post_view_page.dart
  lib/pages/user_page.dart
  lib/pages/user_view_page.dart
  lib/utils/handle_hidden.dart
  lib/widgets/post_preview.dart
Labels: enhancement

#60 Feature/snackbar notification
  lib/pages/post_list_show_page.dart
  lib/widgets/pop_up_menu_buttons.dart
  lib/widgets/snackbar_noti.dart
Labels: enhancement

#62 Delete(user_page.dart): 유저 정보 조회하는 코드 삭제.
  lib/pages/user_page.dart
Labels: chore

#61 Fix(buleetin_search_page.dart): 검색 오류 수정
  lib/pages/bulletin_search_page.dart
Labels: bug

#67 is_hidden=true일 때 자신의 글 수정 불가능하게 변경
  lib/pages/post_view_page.dart
Labels: bug

#57 PostWritePage 디자인 향상
  lib/main.dart
  lib/pages/post_write_page.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#64 UserViewPage 무한로딩 해결
  lib/pages/post_view_page.dart
  lib/pages/user_view_page.dart
Labels: bug

#68 포탈 공지글 북마크 추가
  lib/pages/post_view_page.dart
Labels: enhancement

#71 Fix(post_view_page.dart): 댓글 닉네임 maxWidth 수정
  lib/pages/post_view_page.dart
Labels: bug

#81 Chore: add build github actions
  .github/workflows/build.yml
  android/.gitignore
  android/ci.jks
Labels: chore

#87 좋아요, 싫어요 반응속도 빠르게 하기
  ios/Podfile.lock
  lib/pages/post_view_page.dart
  lib/providers/user_provider.dart
  lib/utils/post_view_utils.dart
Labels: enhancement

#89 '<', '>' 표시 문제 해결
  lib/pages/post_view_page.dart
Labels: bug

#100 PostViewPage Android webview crash 해결
  lib/widgets/in_article_web_view.dart
Labels: bug
