Repository sparcs-kaist/new-ara-app, pull requests merged in 2024-08, with the labels that each got.

#209 195 decorate last item message
  assets/translations/en.json
  assets/translations/ko.json
  lib/pages/post_list_show_page.dart
  lib/translations/codegen_loader.g.dart
  lib/translations/locale_keys.g.dart
Labels: enhancement

#213 feat: decorate last item
  lib/pages/post_list_show_page.dart
Labels: enhancement, good first issue

#217 fix: comment HTML issue
  lib/utils/html_info.dart
Labels: bug

#212 [Feature] caching for post write page
  assets/translations/en.json
  assets/translations/ko.json
  lib/pages/post_write_page.dart
  lib/translations/codegen_loader.g.dart
  lib/translations/locale_keys.g.dart
  lib/widgets/dialogs.dart
Labels: enhancement

#216 Chore/add fastlane cd
  .github/workflows/deploy.yml
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  pubspec.yaml
Labels: chore

#215 [Hotfix] PostWritePage 첨부파일 업로드 기능 복구 & Target API Version 업데이트
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/pages/post_write_page.dart
  lib/utils/slide_routing.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, chore

#218 deploy workflow 버그 수정
  .github/workflows/deploy.yml
Labels: bug

#220 main으로 push한 수정사항을 dev에도 반영
  android/app/build.gradle
  lib/pages/post_write_page.dart
  pubspec.lock
  pubspec.yaml
Labels: bug
